#!/bin/bash
# kodcms migration scripts

GREEN='\033[0;32m'
NC='\033[0m' #no color

outputPath=$(pwd)"/exported/"
mkdir -p $outputPath;
chmod 0777 -vR $outputPath;

display_size(){
du -h --max-depth=1 --exclude=./.git
}

export_db(){
printf "\n ${GREEN} Step one \t Dump mysql database\n"

#read username
read -p  'Mysql Username:' mysqlUser


#read database name
read -p 'Mysql database name: ' mysqlDb
echo
# export database
	mysqldump -u $mysqlUser -p $mysqlDb > ${outputPath}/db.sql  --no-tablespaces;
echo "Db Exported"
echo
display_size
echo

}


zip_sourcecode(){
echo "Admin right needed"
echo
printf "\n${GREEN} Step Two \t Zip source code.\n\n"

webdir="/var/www/${cmsDomain}/web"

if [ -d $webdir ]

 then

cd $webdir;
echo "${webdir} access granted!"
echo
sudo ls 2>&1;
echo
#zip website
[[ -d ${outputPath}kodcms.zip ]] &&  rm  kodcms.zip ;
if ! sudo zip -o -r ${outputPath}kodcms.zip ./* -x "./error" "cms/vendor/*" "cms/web/*" "cms/src/runtime/*" "cms/src/storage/*" "cms/src/tests" "cms/src/vagrant" "cms/src/*.sql" "cms/template" "cms/clientAssets" "cms/.idea" "website/web/assets/*" "website/resources/*" "website/runtime/*"  2>&1; then
printf "\n Unable to zip source code.  \n check if source code available \n or  try again. "
else
chmod 0777 ${outputPath}kodcms.zip;
printf "\n${NC} Source code Exported \n\n ${GREEN}"
fi


cd $outputPath;
ls
echo
echo $(pwd)
echo
echo "Total sized"
display_size
echo

else
printf "\n Website not found\n"
fi;


}

server_script(){

#files to be uploads
scriptPath=$(pwd)/exported
sourceCode=$scriptPath/kodcms.zip
databaseSql=$scriptPath/db.sql
##script file which will run on server onece

dbConfigFile=$scriptPath/db.php
installScriptFile=""


read -p "Enter remote server address: " target_host
read -p "Enter remote server username: " userName;
#read -sp "Enter ${userName}@${target_host} password: " password
read -p "Enter server web root path: " webroot

#copy files to server

copy_files(){
printf "\n${GREEN}Copying Source code, db.php and database to server"
echo
chmod 0777 $dbConfigFile;
# sshpass -p $password
 if  ! scp  -o StrictHostKeyChecking=no  {$sourceCode,$databaseSql,$dbConfigFile} $userName@$target_host:$webroot 2>&1;then
echo "Cannot copy files. Please try again"
else
echo "Sourcecode copied"
fi
echo
echo 



}

create_db_config(){
touch $dbConfigFile;
FILE=$dbConfigFile;
read -p 'Database UserName: ' dbUser;
read -p "Database Password for ${dbUser}: " dbpwd;
read -p 'Database Name: ' dbName
/bin/cat <<EOM >$FILE
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=$dbName',
    'username' => '$dbUser',
    'password' => '$dbpwd',
    'charset' => 'utf8',
    'enableSchemaCache' => true,
    'schemaCacheDuration' => 60,
    'schemaCache' => 'cache',
];

EOM

echo
echo "kodcms Database configuration for production file created "
echo
}


#access to server
server_access(){
    echo "Script to run on server"
    echo
#initDbScript=$(pwd)/database.sh
#sshpass -p $password 
ssh  $userName@$target_host "cd ${webroot}; dbUser=${dbUser}; dbName=${dbName}; bash" << EOF
if unzip -o ./kodcms.zip 2>&1;
then
rm ./kodcms.zip
echo "Zip removed"
echo
chmod 0777 -vR ./website/runtime
echo "Website runtime permission changed"
echo
chmod 0777 -vR ./website/web/media
echo "Website web permission changed"
echo
chmod 0777 -vR ./website/storage
echo "Website storage permission changed"
echo
chmod 0777 -vR ./plugins/*/*.json
echo "plugins permission changed"
echo
mv ./db.php website/config/db.php 2>&1
echo "db.php moved top website"
echo
mkdir -m 777 ./website/web/assets 
echo "Assets directory created"
echo
mkdir -m 777 ./website/runtime
echo "runtime directory created"
else
echo "Unable to unzip source code!"
echo
fi

EOF
}



init_hosts(){

echo "Server initialized"
echo
    create_db_config 2>&1
    copy_files 2>&1
    server_access 2>&1
}



validate_file(){
# check if file exists

if [[ -f $sourceCode && -f $databaseSql ]] 2>&1; then
    init_hosts
    else

    echo "Files not found! Please Export it."
    exit 0;
fi


}





validate_file

}



printf "\n\nWelcome to kodCms migration tool. \tBy: Ronash Dhakal\n";
read -p 'Enter Domain name without www: ' cmsDomain

printf "\n${GREEN}What would you like to do?\n"
PS3='Please enter your choice: '
options=("Export Database" "Export Source Code" "Upload to server" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Export Database")
            export_db
            ;;
        "Export Source Code")
		zip_sourcecode
            ;;
	"Upload to server")
	server_script
	;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

#exit 0













