#!/bin/bash
# kodcms migration scripts
GREEN='\033[0;32m'
NC='\033[0m' #no color
outputPath=$(pwd)"/exported/"
mkdir -m 777 -p $outputPath ;
chmod 0777 -vR $outputPath;

display_size(){
du -h --max-depth=1 --exclude=./.git
}

. ./inc/exportDb.sh
. ./inc/zip_source_code.sh
. ./inc/server_script.sh

validate_file(){
# check if file exists
if [[ -f $sourceCode && -f $databaseSql ]]; then
    init_hosts
    else

    echo "Files not found! Please Export it."
    exit 0;
fi
}

validate_file

}

printf "\n\nWelcome to kodCms migration tool. \tBy: Ronash Dhakal\n";
read -p 'Enter Domain name without www: ' cmsDomain

printf "\n${GREEN}What would you like to do?\n"
PS3='Please enter your choice: '
options=("Export Database" "Export Source Code" "Upload to server" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Export Database")
            export_db
            ;;
        "Export Source Code")
		zip_sourcecode
            ;;
	"Upload to server")
	server_script
	;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done